version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  deploy:
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm test
      - run: ssh -o "StrictHostKeyChecking no" ec2-user@ec2-3-84-220-134.compute-1.amazonaws.com "cd ~/source; git checkout -- package-lock.json; git pull; npm install; npx pm2 restart index.js"

workflows:
  build-test-deploy:
    jobs:
      - deploy
